services:
  # FastAPI Token Service
  - type: web
    name: spiritual-token-api
    env: python
    buildCommand: |
      cd python-voice-agent &&
      pip install --upgrade pip &&
      pip install -r requirements.txt
    startCommand: |
      cd python-voice-agent &&
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: LIVEKIT_URL
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
    
  # LiveKit Agent Worker
  - type: worker
    name: spiritual-agent-worker
    env: python
    buildCommand: |
      cd python-voice-agent &&
      pip install --upgrade pip &&
      pip install -r requirements.txt
    startCommand: |
      cd python-voice-agent &&
      python app/agents/spiritual_worker.py
    envVars:
      - key: LIVEKIT_URL
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: RENDER
        value: "true"
    # Worker-specific settings
    autoDeploy: true
    numInstances: 1  # Start with 1, scale as needed
    plan: starter  # Upgrade to standard/pro for production 